version: '2'

services:
  config:
    build: config-server/
    ports:
      - 8888:8888
    networks:
      - net
    hostname: config
    container_name: config 
    external_links:
      - elk
      - kafka

  eureka:
    build: eureka-server/
    ports:
      - 8010:8010
    networks:
      - net
    depends_on:
      - config
    hostname: eureka
    container_name: eureka  
    command: ["./wait-for-it.sh","config:8888","--timeout=100","--","/usr/local/bin/start.sh"]
    external_links:
      - elk

  reminder:
    image: todo/reminder-service
    ports:
      - 8015:8015
    networks:
      - net
    depends_on:
      - eureka
      - admin
    hostname: reminder
    command: ["./wait-for-it.sh","config:8888","--timeout=100","--","/usr/local/bin/start.sh"]
    external_links:
      - elk
      - kafka
      
  user:
    build: user-service/
    ports:
      - 8016:8016
    networks:
      - net
    depends_on:
      - eureka
      - admin
    hostname: user
    container_name: user
    command: ["./wait-for-it.sh","config:8888","--timeout=500","--","/usr/local/bin/start.sh"]
    external_links:
      - elk
      - kafka

  oauth:
    build: oauth-server/
    ports:
      - 8017:8017
    networks:
      - net
    depends_on:
      - eureka
      - user
      - admin
    hostname: oauth
    container_name: oauth
    command: ["./wait-for-it.sh","config:8888","--timeout=500","--","/usr/local/bin/start.sh"]
    external_links:
      - elk
    

  gateway:
    build: api-gateway/
    ports:
      - 8018:8018
    networks:
      - net
    depends_on:
      - eureka
      - admin
    hostname: gateway
    command: ["./wait-for-it.sh","config:8888","--timeout=500","--","/usr/local/bin/start.sh"]
    external_links:
      - elk

  mail:
    build: mail-service/
    ports:
      - 8020:8020
    networks:
      - net
    depends_on:
      - eureka
      - admin
    hostname: mail
    container_name: mail
    command: ["./wait-for-it.sh","config:8888","--timeout=500","--","/usr/local/bin/start.sh"]
    external_links:
      - elk
      - kafka

  admin:
    build:
      context: ./admin-server
      dockerfile: ./Dockerfile
    depends_on:
      - eureka
    container_name: admin
    ports:
      - 8026:8026
    networks:
      - net
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8010
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - LOGGING_FILE=/tmp/admin.log
    command: ["./wait-for-it.sh","config:8888","--timeout=500","--","/usr/local/bin/start.sh"]
    external_links:
      - elk

  proxy:
    build: proxy/
    ports:
      - 80:80
    networks:
      - net
    depends_on:
      - gateway
    hostname: proxy
    container_name: proxy  

volumes:
  todo_data:
    external: true
  todo_elk:
    external: true

networks:
  net:
    driver: bridge
