spring:
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        output:
          destination: todo-mail
          content-type: application/json
      kafka:
        binder:
          brokers: ${SERVICE_REGISTRY_HOST:kafka}
          zkNodes: ${SERVICE_REGISTRY_HOST:zookeeper}
          defaultZkPort: 2181
          defaultBrokerPort: 9092
server:
  port: 8030