---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: 8021
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: oauth,user,todo,mailer

management:
  port: 8990  
