---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka:8010/eureka/,http://localhost:8010/eureka/
server:
  port: 8022
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: oauth,user,todo,mailer

management:
  port: 8990  
